package com.soukmar.app.ui.model

import androidx.compose.ui.graphics.Color
import java.text.NumberFormat
import java.time.Duration
import java.time.Instant
import java.time.format.DateTimeParseException
import java.util.Locale

/** Mirrors soukmar/src/app/models/listing.model.ts's CATEGORIES/CONDITION_CATEGORIES/
 * HIGHLIGHT_ATTR_CODES — keep in sync when the catalog changes. Labels are
 * French only for now (the app has no i18n layer yet, unlike the web app). */
data class CategoryConfig(
    val value: String,
    val label: String,
    val emoji: String,
    val bg: Color,
    val fg: Color
)

val CATEGORIES: List<CategoryConfig> = listOf(
    CategoryConfig("VEHICLES", "Véhicules", "🚗", Color(0xFFDBEAFE), Color(0xFF1D4ED8)),
    CategoryConfig("REAL_ESTATE", "Immobilier", "🏠", Color(0xFFDCFCE7), Color(0xFF15803D)),
    CategoryConfig("JOBS", "Emploi", "💼", Color(0xFFF3E8FF), Color(0xFF7E22CE)),
    CategoryConfig("ELECTRONICS", "Électronique", "📱", Color(0xFFFEF9C3), Color(0xFFA16207)),
    CategoryConfig("HOME_GARDEN", "Maison & Jardin", "🌿", Color(0xFFD1FAE5), Color(0xFF065F46)),
    CategoryConfig("FASHION", "Mode", "👗", Color(0xFFFCE7F3), Color(0xFFBE185D)),
    CategoryConfig("SERVICES", "Services", "🔧", Color(0xFFFFEDD5), Color(0xFFC2410C)),
    CategoryConfig("OTHER", "Autres", "📦", Color(0xFFF1F5F9), Color(0xFF475569)),
    CategoryConfig("BABY_KIDS", "Bébé & Enfants", "🧸", Color(0xFFCCFBF1), Color(0xFF0F766E)),
    CategoryConfig("PETS", "Animaux", "🐾", Color(0xFFF5E9D9), Color(0xFF92603A)),
    CategoryConfig("SPORTS_LEISURE", "Sport & Loisirs", "⚽", Color(0xFFE0E7FF), Color(0xFF4338CA)),
    CategoryConfig("LESSONS_COURSES", "Cours & Leçons", "📚", Color(0xFFCFFAFE), Color(0xFF0E7490)),
    CategoryConfig("CARPOOLING", "Covoiturage", "🚕", Color(0xFFDBEAFE), Color(0xFF1D4ED8)),
    CategoryConfig("TRANSPORT", "Transport", "🚛", Color(0xFFFFEDD5), Color(0xFFC2410C)),
    CategoryConfig("RENTAL", "Location", "🚙", Color(0xFFF3E8FF), Color(0xFF7E22CE)),
    CategoryConfig("TICKETS", "Billets & Tickets", "🎫", Color(0xFFFEF9C3), Color(0xFFA16207)),
    CategoryConfig("GIVEAWAY_SWAP", "Dons & Échanges", "🎁", Color(0xFFDCFCE7), Color(0xFF15803D)),
    CategoryConfig("MOVING", "Déménagement", "🚚", Color(0xFFF5E9D9), Color(0xFF92603A)),
)

fun categoryConfig(value: String): CategoryConfig? = CATEGORIES.find { it.value == value }

/** Best-effort display label for a catalog code (subcategory, attribute,
 * SELECT option) when there's no i18n string for it yet — e.g. "FUEL_TYPE"
 * -> "Fuel type". Same convention already used ad hoc in ListingDetailScreen. */
fun humanizeCode(code: String): String = code.lowercase().replace('_', ' ').replaceFirstChar { it.uppercase() }

/** Mirrors listing.model.ts's isNewListing() — true for the first 24h after creation. */
fun isNewListing(createdAt: String, hours: Long = 24): Boolean {
    val created = try { Instant.parse(createdAt) } catch (e: DateTimeParseException) { return false }
    val ms = Duration.between(created, Instant.now()).toMillis()
    return ms in 0 until hours * 3_600_000
}

val CONDITION_CATEGORIES: Set<String> = setOf(
    "VEHICLES", "ELECTRONICS", "HOME_GARDEN", "FASHION", "BABY_KIDS", "SPORTS_LEISURE", "GIVEAWAY_SWAP"
)

/** Mirrors MOROCCO_CITIES in listing.model.ts (deduplicated + sorted there via
 * `.sort()` on an array that repeats several city names across regions). */
val MOROCCO_CITIES: List<String> = listOf(
    // Grand Casablanca-Settat
    "Casablanca", "Mohammedia", "El Jadida", "Settat", "Berrechid", "Benslimane",
    "Médiouna", "Nouaceur", "Bouskoura", "Dar Bouazza", "Oulad Teima",
    "Azemmour", "Haouzia", "Sidi Bennour", "Khémis Zemamra", "Oulad Frej",
    "Bir Jdid", "Lqliaa", "Sidi Smail", "Oulad Amrane", "Had Soualem",
    "Echemmaia", "Sidi Rahhal", "Bouznika", "Benhmed", "Oulad Abbou",
    // Rabat-Salé-Kénitra
    "Rabat", "Salé", "Kénitra", "Khémisset", "Sidi Kacem", "Sidi Slimane",
    "Sidi Yahia du Gharb", "Lalla Mimouna", "Mechra Bel Ksiri", "Jorf El Melha",
    "Ouazzane", "Had Kourt", "Aïn Johra", "Tiflet", "Rommani", "Maaziz",
    "Souk el Arbaa", "Moulay Bousselham", "Sidi Allal Tazi", "Arbaoua",
    // Fès-Meknès
    "Fès", "Meknès", "Taza", "Ifrane", "Azrou", "Moulay Yacoub",
    "El Hajeb", "Aïn Taoujdate", "Missour", "Boulemane", "Guercif",
    "Sefrou", "Imouzzer Kandar", "Almis Marmoucha", "Aïn Leuh",
    "Boulmane du Dadès", "Tahla", "Ain Bni Mathar", "Itzer", "Rich",
    // Marrakech-Safi
    "Marrakech", "Safi", "Essaouira", "Kelaa des Sraghna", "Chichaoua",
    "Youssoufia", "Rehamna", "Ben Guerir", "Tamansourt", "Ait Ourir",
    "Amizmiz", "Tahannaout", "Tahnaout", "Asni", "Tighedouine",
    "Ouarzazate", "Kelaa M'Gouna", "Skoura", "Agdz", "Zagora", "M'Hamid",
    "Tinzouline", "Tamegroute", "Taroudant", "Aoulouz",
    "Biougra", "Aït Baha", "Massa", "Imintanoute", "Imi n'Tlit",
    // Souss-Massa
    "Agadir", "Inezgane", "Aït Melloul", "Tiznit", "Chtouka Aït Baha",
    "Bensergao", "Drarga", "Tafraout",
    "Sidi Ifni", "Guelmim", "Tan-Tan", "Sidi Bibi", "Sebt Aït Ahmed",
    "Oulad Dahou", "Aït Iaazza", "Aït Amira", "Dcheira El Jihadia",
    // Tanger-Tétouan-Al Hoceïma
    "Tanger", "Tétouan", "Al Hoceïma", "Chefchaouen", "Larache", "Asilah",
    "Fnideq", "Martil", "Mdiq", "Oued Laou", "Bab Berred", "Brikcha",
    "Jebha", "Targuist", "Imzouren", "Bni Bouayach", "Rif",
    "Ksar El Kébir", "Souk El Arbaa du Rharb", "Zouada", "Ain Defali",
    // Oriental
    "Oujda", "Nador", "Berkane", "Taourirt", "Jerada", "Figuig",
    "Bouarfa", "Aïn Bni Mathar", "Ras El Ma", "Debdou", "Aïn Sfa",
    "Zaïo", "Selouane", "Ben Taïeb", "Saidia", "Aklim", "Boudnib",
    "Guenfouda", "Ahfir", "Garéat Ben Ouali", "Touissit",
    // Béni Mellal-Khénifra
    "Béni Mellal", "Khouribga", "Fquih Ben Salah", "Azilal", "Kasba Tadla",
    "Oued Zem", "Boujad", "El Ksiba", "Demnate", "Aït Attab",
    "Bzou", "Rahhal", "Souk Sebt Oulad Nemma", "El Brouj",
    "Oulad Ayad", "Afourer", "Bni Ayat", "Timoulilt",
    // Drâa-Tafilalet
    "Errachidia", "Tinghir", "Midelt",
    "Er-Rich", "Goulmima", "Erfoud", "Rissani", "Merzouga",
    "Aoufous", "Arfoud", "Jorf", "Ksar Souk", "Alnif", "Ghris",
    "Tinjdad", "Tinejdad", "Iknioun",
    // Laâyoune-Sakia El Hamra
    "Laâyoune", "Boujdour", "Smara", "Tarfaya", "Foum El Oued",
    "Dakhla",
    // Guelmim-Oued Noun
    "Assa", "Zag", "Tata",
    "Akka", "Foum Zguid", "Tissint",
    // Eddakhla-Oued Dahab
    "Aousserd", "Bir Gandouz",
    // Villes supplémentaires et communes
    "Ouled Teima", "Aïn Harrouda", "Mansouria", "Aïn Chock", "Hay Hassani",
    "Ben Msik", "Sidi Bernoussi", "Aïn Sebaâ", "Sidi Moumen",
    "Oulfa", "Bel Air", "Anfa", "Maarif", "Gauthier",
    "Agdal", "Hassan", "Souissi", "Hay Riad", "Yacoub El Mansour",
    "Temara", "Aïn Atiq", "Skhirat", "Harhoura",
    "Aouinet Torkoz", "Taghazout", "Aglou", "Mirleft",
    "Legzira", "Souss", "Tasila", "Imi Mqorn",
    "Imsouane", "Tamraght", "Aourir",
    "Belfaa", "Ait Baamrane",
    "Warzazat", "Tazzarine", "Nkob", "Mhamid El Ghizlane",
    "Akka Ighane", "Icht",
    "Bou Izakarn", "Ifrane Anti-Atlas", "Aït Herbil",
    "Souk El Had", "Had Hrara", "Tamzaourt", "Tikki", "Imourane",
    "Oued Souss", "Tikiouine", "Tassila",
    "Dcheira", "Sebt Gzoula",
    "Sebt Jahjouh", "Sidi L'Mokhtar", "Jemâa Shaïm",
    "Abda", "Ounagha", "Ida Ougnidif", "Chiadma",
    "Chemaia", "Lalla Fatna",
    "Sidi Aïssa Ben Slimane", "Tlat Hanchane",
    "Oulad Berhil", "Tassaout", "Aït Ourirr",
    "Tnine Chtouka", "Tnine Aït Ourir", "Tnine Sidi Yamani",
    "Moulay Abdallah", "Moulay Brahim", "Moulay Idriss Zerhoun",
    "Sidi Harazem", "Sidi Bettache", "Sidi Bouknadel",
    "Sidi Yahia el Gharb", "Sidi Allal Bahraoui",
    "Sidi Mohamed Ben Abdallah", "Sidi Taibi", "Sidi Yahia Zaer",
    "Aïn El Aouda", "Aïn Cheggag",
    "Aït Oumghar",
    "Zaïda", "Mrirt", "Khenifra", "Aït Ishaq",
    "El Kbab", "Timahdite",
    "Ain Aicha", "Taounate", "Ghafsai", "Rhafsai",
    "Aïn Mediouna", "Galaz", "Arbala", "Zoumi",
    "Derdara", "Bab Taza",
    "Dar Chaoui", "Ain Bahja",
    "Tlat Taghramt", "Ametrasse",
    "Fifi", "Irherm", "Askaoun",
    "Aït Oujane", "Aït Benhaddou",
).distinct().sorted()

/** Arabic city names — Morocco has no city id/code, so this stays a
 * display-only lookup, mirrors listing.model.ts's MOROCCO_CITIES_AR. */
val MOROCCO_CITIES_AR: Map<String, String> = mapOf(
  "Casablanca" to "الدار البيضاء",
  "Mohammedia" to "المحمدية",
  "El Jadida" to "الجديدة",
  "Settat" to "سطات",
  "Berrechid" to "برشيد",
  "Benslimane" to "بنسليمان",
  "Médiouna" to "مديونة",
  "Nouaceur" to "النواصر",
  "Bouskoura" to "بوسكورة",
  "Dar Bouazza" to "دار بوعزة",
  "Oulad Teima" to "أولاد تايمة",
  "Azemmour" to "أزمور",
  "Haouzia" to "الحوزية",
  "Sidi Bennour" to "سيدي بنور",
  "Khémis Zemamra" to "خميس الزمامرة",
  "Oulad Frej" to "أولاد فرج",
  "Bir Jdid" to "بير الجديد",
  "Lqliaa" to "القليعة",
  "Sidi Smail" to "سيدي اسماعيل",
  "Oulad Amrane" to "أولاد عمران",
  "Had Soualem" to "حد السوالم",
  "Echemmaia" to "الشماعية",
  "Sidi Rahhal" to "سيدي رحال",
  "Bouznika" to "بوزنيقة",
  "Benhmed" to "بنحمد",
  "Oulad Abbou" to "أولاد عبو",
  "Rabat" to "الرباط",
  "Salé" to "سلا",
  "Kénitra" to "القنيطرة",
  "Khémisset" to "الخميسات",
  "Sidi Kacem" to "سيدي قاسم",
  "Sidi Slimane" to "سيدي سليمان",
  "Sidi Yahia du Gharb" to "سيدي يحيى الغرب",
  "Lalla Mimouna" to "لالة ميمونة",
  "Mechra Bel Ksiri" to "مشرع بلقصيري",
  "Jorf El Melha" to "جرف الملحة",
  "Ouazzane" to "وزان",
  "Had Kourt" to "حد كورت",
  "Aïn Johra" to "عين جوهرة",
  "Tiflet" to "تيفلت",
  "Rommani" to "الرماني",
  "Maaziz" to "معزيز",
  "Souk el Arbaa" to "سوق الأربعاء",
  "Moulay Bousselham" to "مولاي بوسلهام",
  "Sidi Allal Tazi" to "سيدي علال التازي",
  "Arbaoua" to "أربعاوة",
  "Fès" to "فاس",
  "Meknès" to "مكناس",
  "Taza" to "تازة",
  "Ifrane" to "إفران",
  "Azrou" to "أزرو",
  "Moulay Yacoub" to "مولاي يعقوب",
  "El Hajeb" to "الحاجب",
  "Aïn Taoujdate" to "عين تاوجطات",
  "Missour" to "ميسور",
  "Boulemane" to "بولمان",
  "Guercif" to "جرسيف",
  "Sefrou" to "صفرو",
  "Imouzzer Kandar" to "إموزار كندر",
  "Almis Marmoucha" to "ألميس مرموشة",
  "Aïn Leuh" to "عين اللوح",
  "Boulmane du Dadès" to "بومالن دادس",
  "Tahla" to "تهلة",
  "Ain Bni Mathar" to "عين بني مطهر",
  "Itzer" to "إيتزر",
  "Rich" to "الريش",
  "Marrakech" to "مراكش",
  "Safi" to "آسفي",
  "Essaouira" to "الصويرة",
  "Kelaa des Sraghna" to "قلعة السراغنة",
  "Chichaoua" to "شيشاوة",
  "Youssoufia" to "اليوسفية",
  "Rehamna" to "الرحامنة",
  "Ben Guerir" to "بنجرير",
  "Tamansourt" to "تامنصورت",
  "Ait Ourir" to "أيت أورير",
  "Amizmiz" to "أمزميز",
  "Tahannaout" to "تحناوت",
  "Tahnaout" to "تحناوت",
  "Asni" to "أسني",
  "Tighedouine" to "تغدوين",
  "Ouarzazate" to "ورزازات",
  "Kelaa M'Gouna" to "قلعة مكونة",
  "Skoura" to "سكورة",
  "Agdz" to "أكدز",
  "Zagora" to "زاكورة",
  "M'Hamid" to "امحاميد",
  "Tinzouline" to "تنزولين",
  "Tamegroute" to "تامكروت",
  "Taroudant" to "تارودانت",
  "Aoulouz" to "أولوز",
  "Biougra" to "بيوكرى",
  "Aït Baha" to "أيت باها",
  "Massa" to "ماسة",
  "Imintanoute" to "إمنتانوت",
  "Imi n'Tlit" to "إيمي نتليت",
  "Agadir" to "أكادير",
  "Inezgane" to "إنزكان",
  "Aït Melloul" to "أيت ملول",
  "Tiznit" to "تزنيت",
  "Chtouka Aït Baha" to "الشتوكة أيت باها",
  "Bensergao" to "بنسركاو",
  "Drarga" to "دراركة",
  "Tafraout" to "تافراوت",
  "Sidi Ifni" to "سيدي إفني",
  "Guelmim" to "كلميم",
  "Tan-Tan" to "طانطان",
  "Sidi Bibi" to "سيدي بيبي",
  "Sebt Aït Ahmed" to "سبت أيت أحمد",
  "Oulad Dahou" to "أولاد داهو",
  "Aït Iaazza" to "أيت إيعزة",
  "Aït Amira" to "أيت عميرة",
  "Dcheira El Jihadia" to "الدشيرة الجهادية",
  "Tanger" to "طنجة",
  "Tétouan" to "تطوان",
  "Al Hoceïma" to "الحسيمة",
  "Chefchaouen" to "شفشاون",
  "Larache" to "العرائش",
  "Asilah" to "أصيلة",
  "Fnideq" to "الفنيدق",
  "Martil" to "مرتيل",
  "Mdiq" to "المضيق",
  "Oued Laou" to "واد لاو",
  "Bab Berred" to "باب برد",
  "Brikcha" to "بريكشة",
  "Jebha" to "جبها",
  "Targuist" to "تارجيست",
  "Imzouren" to "إمزورن",
  "Bni Bouayach" to "بني بوعياش",
  "Rif" to "الريف",
  "Ksar El Kébir" to "القصر الكبير",
  "Souk El Arbaa du Rharb" to "سوق الأربعاء الغرب",
  "Zouada" to "الزوادة",
  "Ain Defali" to "عين الدفالي",
  "Oujda" to "وجدة",
  "Nador" to "الناظور",
  "Berkane" to "بركان",
  "Taourirt" to "تاوريرت",
  "Jerada" to "جرادة",
  "Figuig" to "فكيك",
  "Bouarfa" to "بوعرفة",
  "Aïn Bni Mathar" to "عين بني مطهر",
  "Ras El Ma" to "رأس الماء",
  "Debdou" to "دبدو",
  "Aïn Sfa" to "عين الصفا",
  "Zaïo" to "زايو",
  "Selouane" to "سلوان",
  "Ben Taïeb" to "بن الطيب",
  "Saidia" to "السعيدية",
  "Aklim" to "أكليم",
  "Boudnib" to "بودنيب",
  "Guenfouda" to "قنفودة",
  "Ahfir" to "أحفير",
  "Garéat Ben Ouali" to "كارية بن علي",
  "Touissit" to "تويسيت",
  "Béni Mellal" to "بني ملال",
  "Khouribga" to "خريبكة",
  "Fquih Ben Salah" to "الفقيه بن صالح",
  "Azilal" to "أزيلال",
  "Kasba Tadla" to "قصبة تادلة",
  "Oued Zem" to "وادي زم",
  "Boujad" to "بوجاد",
  "El Ksiba" to "القصيبة",
  "Demnate" to "دمنات",
  "Aït Attab" to "أيت عتاب",
  "Bzou" to "بزو",
  "Rahhal" to "الرحالة",
  "Souk Sebt Oulad Nemma" to "سوق السبت أولاد النمة",
  "El Brouj" to "البروج",
  "Oulad Ayad" to "أولاد عياد",
  "Afourer" to "أفورار",
  "Bni Ayat" to "بني عياط",
  "Timoulilt" to "تيموليلت",
  "Errachidia" to "الرشيدية",
  "Tinghir" to "تنغير",
  "Midelt" to "ميدلت",
  "Er-Rich" to "الريش",
  "Goulmima" to "كلميمة",
  "Erfoud" to "أرفود",
  "Rissani" to "الريصاني",
  "Merzouga" to "مرزوكة",
  "Aoufous" to "أوفوس",
  "Arfoud" to "أرفود",
  "Jorf" to "الجرف",
  "Ksar Souk" to "قصر السوق",
  "Alnif" to "ألنيف",
  "Ghris" to "غريس",
  "Tinjdad" to "تنجداد",
  "Tinejdad" to "تنجداد",
  "Iknioun" to "إكنيون",
  "Laâyoune" to "العيون",
  "Boujdour" to "بوجدور",
  "Smara" to "السمارة",
  "Tarfaya" to "طرفاية",
  "Foum El Oued" to "فم الواد",
  "Dakhla" to "الداخلة",
  "Assa" to "أسا",
  "Zag" to "الزاك",
  "Tata" to "طاطا",
  "Akka" to "أكا",
  "Foum Zguid" to "فم زكيد",
  "Tissint" to "تيسينت",
  "Aousserd" to "أوسرد",
  "Bir Gandouz" to "بئر كندوز",
  "Ouled Teima" to "أولاد تايمة",
  "Aïn Harrouda" to "عين حرودة",
  "Mansouria" to "المنصورية",
  "Aïn Chock" to "عين الشق",
  "Hay Hassani" to "الحي الحسني",
  "Ben Msik" to "بن مسيك",
  "Sidi Bernoussi" to "سيدي البرنوصي",
  "Aïn Sebaâ" to "عين السبع",
  "Sidi Moumen" to "سيدي مومن",
  "Ain Chock" to "عين الشق",
  "Oulfa" to "أولفة",
  "Bel Air" to "بلير",
  "Anfa" to "أنفا",
  "Maarif" to "المعاريف",
  "Gauthier" to "غوتييه",
  "Agdal" to "أكدال",
  "Hassan" to "حسان",
  "Souissi" to "السويسي",
  "Hay Riad" to "حي الرياض",
  "Yacoub El Mansour" to "يعقوب المنصور",
  "Temara" to "تمارة",
  "Aïn Atiq" to "عين عتيق",
  "Skhirat" to "الصخيرات",
  "Harhoura" to "هرهورة",
  "Aouinet Torkoz" to "عوينة تركوز",
  "Taghazout" to "تغازوت",
  "Aglou" to "أكلو",
  "Mirleft" to "ميرلفت",
  "Legzira" to "لكزيرة",
  "Souss" to "سوس",
  "Tasila" to "تاسيلة",
  "Imi Mqorn" to "إيمي مقورن",
  "Imsouane" to "إمسوان",
  "Tamraght" to "تمغارت",
  "Aourir" to "أوريار",
  "Belfaa" to "بلفاع",
  "Ait Baamrane" to "أيت باعمران",
  "Warzazat" to "ورزازات",
  "Tazzarine" to "تازارين",
  "Nkob" to "نكوب",
  "Mhamid El Ghizlane" to "امحاميد الغزلان",
  "Akka Ighane" to "أكا إغان",
  "Icht" to "إيشت",
  "Bou Izakarn" to "بويزكارن",
  "Ifrane Anti-Atlas" to "إفران الأطلس الصغير",
  "Aït Herbil" to "أيت هربيل",
  "Souk El Had" to "سوق الحد",
  "Had Hrara" to "حد حرارة",
  "Tamzaourt" to "تامزاورت",
  "Tikki" to "تيكي",
  "Imourane" to "إموران",
  "Oued Souss" to "وادي سوس",
  "Tikiouine" to "تيكيوين",
  "Tassila" to "تاسيلة",
  "Dcheira" to "الدشيرة",
  "Sebt Gzoula" to "سبت اكزولة",
  "Sebt Jahjouh" to "سبت الجحاجحة",
  "Sidi L'Mokhtar" to "سيدي المختار",
  "Jemâa Shaïm" to "جمعة شايم",
  "Abda" to "عبدة",
  "Ounagha" to "أوناغة",
  "Ida Ougnidif" to "إدا وكنيدف",
  "Chiadma" to "الشياظمة",
  "Chemaia" to "الشماعية",
  "Lalla Fatna" to "لالة فاطنة",
  "Sidi Aïssa Ben Slimane" to "سيدي عيسى بن سليمان",
  "Tlat Hanchane" to "تلات الهنشان",
  "Oulad Berhil" to "أولاد برحيل",
  "Tassaout" to "تاسوت",
  "Aït Ourirr" to "أيت أورير",
  "Tnine Chtouka" to "اثنين الشتوكة",
  "Tnine Aït Ourir" to "اثنين أيت أورير",
  "Tnine Sidi Yamani" to "اثنين سيدي اليماني",
  "Moulay Abdallah" to "مولاي عبد الله",
  "Moulay Brahim" to "مولاي إبراهيم",
  "Moulay Idriss Zerhoun" to "مولاي إدريس زرهون",
  "Sidi Harazem" to "سيدي حرازم",
  "Sidi Bettache" to "سيدي بطاش",
  "Sidi Bouknadel" to "سيدي بوقنادل",
  "Sidi Yahia el Gharb" to "سيدي يحيى الغرب",
  "Sidi Allal Bahraoui" to "سيدي علال البحراوي",
  "Sidi Mohamed Ben Abdallah" to "سيدي محمد بن عبد الله",
  "Sidi Taibi" to "سيدي الطيبي",
  "Sidi Yahia Zaer" to "سيدي يحيى زعير",
  "Aïn El Aouda" to "عين العودة",
  "Aïn Cheggag" to "عين الشقف",
  "Aït Oumghar" to "أيت أومغار",
  "Zaïda" to "زايدة",
  "Mrirt" to "مريرت",
  "Khenifra" to "خنيفرة",
  "Aït Ishaq" to "أيت إسحاق",
  "El Kbab" to "القباب",
  "Timahdite" to "تيمحضيت",
  "Ain Aicha" to "عين عائشة",
  "Taounate" to "تاونات",
  "Ghafsai" to "غفساي",
  "Rhafsai" to "غفساي",
  "Aïn Mediouna" to "عين مديونة",
  "Galaz" to "كلاز",
  "Arbala" to "أربالة",
  "Zoumi" to "الزومي",
  "Derdara" to "الدردارة",
  "Bab Taza" to "باب تازة",
  "Dar Chaoui" to "دار الشاوي",
  "Ain Bahja" to "عين البهجة",
  "Tlat Taghramt" to "تلات تغرامت",
  "Ametrasse" to "أمتراس",
  "Fifi" to "فيفي",
  "Irherm" to "إغرم",
  "Askaoun" to "أسكاون",
  "Imi N'Tlit" to "إيمي نتليت",
  "Aït Oujane" to "أيت وجان",
  "Aït Benhaddou" to "أيت بن حدو",
)

/** Shows the Arabic name when the app is in Arabic and one exists,
 * otherwise the French/Latin spelling — mirrors listing.model.ts's cityLabel(). */
fun cityLabel(city: String, lang: String): String {
    if (city.isEmpty()) return city
    return if (lang == "ar") MOROCCO_CITIES_AR[city] ?: city else city
}

val HIGHLIGHT_ATTR_CODES: Map<String, List<String>> = mapOf(
    "VEHICLES" to listOf("MILEAGE", "FUEL_TYPE"),
    "ELECTRONICS" to listOf("STORAGE_CAPACITY", "RAM"),
    "REAL_ESTATE" to listOf("LIVING_AREA_SQM", "ROOMS"),
    "FASHION" to listOf("SIZE", "SIZE_EU"),
    "HOME_GARDEN" to listOf("FURNITURE_TYPE"),
    "TICKETS" to listOf("EVENT_DATE", "TICKET_COUNT"),
)

/** Splits a formatted price into amount/currency so the currency can be
 * rendered smaller — mirrors formatPriceParts() in listing.model.ts. */
fun formatPriceParts(price: Double, currency: String = "MAD"): Pair<String, String> {
    val nf = NumberFormat.getIntegerInstance(Locale.FRANCE)
    return nf.format(price) to currency
}

/** French relative-time label, e.g. "il y a 5 min" — mirrors timeAgo() in
 * listing.model.ts (which uses Intl.RelativeTimeFormat, unavailable here). */
fun timeAgo(isoDate: String): String {
    val instant = try { Instant.parse(isoDate) } catch (e: DateTimeParseException) { return "" }
    val seconds = Duration.between(instant, Instant.now()).seconds.coerceAtLeast(0)
    return when {
        seconds < 60 -> "à l'instant"
        seconds < 3600 -> "il y a ${seconds / 60} min"
        seconds < 86400 -> "il y a ${seconds / 3600} h"
        seconds < 2_592_000 -> "il y a ${seconds / 86400} j"
        else -> "il y a ${seconds / 2_592_000} mois"
    }
}
