package com.soukmar.app.ui.model

// Single source of truth for the site-wide "which country am I browsing/
// listing in" concept (Listing.country) — mirrors soukmar/src/app/models/
// country.model.ts and soukmar-backend/src/lib/countries.ts EXACTLY (same
// COUNTRIES array, same CITIES_BY_COUNTRY curated set). Generated from the
// web source via a one-off script rather than hand-transcribed, to avoid
// data-entry drift across ~193 countries. If the web list changes, re-run
// the extraction rather than editing this file by hand.
//
// Codes are ISO 3166-1 alpha-2, same as web, so this stays interchangeable
// with the backend's Listing.country column. Country *names* are never
// hand-translated here — java.util.Locale("", code).getDisplayCountry(uiLocale)
// is the JVM's Intl.DisplayNames equivalent (CLDR-backed), used at call
// sites instead of a hardcoded name table.

enum class ContinentRegion { MOROCCO, AFRICA, EUROPE, ASIA, NORTH_AMERICA, SOUTH_AMERICA, OCEANIA }

data class CountryInfo(val code: String, val region: ContinentRegion, val currency: String)

val COUNTRIES: List<CountryInfo> = listOf(
    CountryInfo("MA", ContinentRegion.MOROCCO, "MAD"),
    CountryInfo("DZ", ContinentRegion.AFRICA, "DZD"),
    CountryInfo("TN", ContinentRegion.AFRICA, "TND"),
    CountryInfo("LY", ContinentRegion.AFRICA, "LYD"),
    CountryInfo("EG", ContinentRegion.AFRICA, "EGP"),
    CountryInfo("SD", ContinentRegion.AFRICA, "SDG"),
    CountryInfo("SS", ContinentRegion.AFRICA, "SSP"),
    CountryInfo("MR", ContinentRegion.AFRICA, "MRU"),
    CountryInfo("ML", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("NE", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("TD", ContinentRegion.AFRICA, "XAF"),
    CountryInfo("SN", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("GM", ContinentRegion.AFRICA, "GMD"),
    CountryInfo("GW", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("GN", ContinentRegion.AFRICA, "GNF"),
    CountryInfo("SL", ContinentRegion.AFRICA, "SLE"),
    CountryInfo("LR", ContinentRegion.AFRICA, "LRD"),
    CountryInfo("CI", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("GH", ContinentRegion.AFRICA, "GHS"),
    CountryInfo("TG", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("BJ", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("NG", ContinentRegion.AFRICA, "NGN"),
    CountryInfo("CM", ContinentRegion.AFRICA, "XAF"),
    CountryInfo("CF", ContinentRegion.AFRICA, "XAF"),
    CountryInfo("GQ", ContinentRegion.AFRICA, "XAF"),
    CountryInfo("GA", ContinentRegion.AFRICA, "XAF"),
    CountryInfo("CG", ContinentRegion.AFRICA, "XAF"),
    CountryInfo("CD", ContinentRegion.AFRICA, "CDF"),
    CountryInfo("AO", ContinentRegion.AFRICA, "AOA"),
    CountryInfo("ZM", ContinentRegion.AFRICA, "ZMW"),
    CountryInfo("MW", ContinentRegion.AFRICA, "MWK"),
    CountryInfo("MZ", ContinentRegion.AFRICA, "MZN"),
    CountryInfo("ZW", ContinentRegion.AFRICA, "ZWL"),
    CountryInfo("BW", ContinentRegion.AFRICA, "BWP"),
    CountryInfo("NA", ContinentRegion.AFRICA, "NAD"),
    CountryInfo("ZA", ContinentRegion.AFRICA, "ZAR"),
    CountryInfo("LS", ContinentRegion.AFRICA, "LSL"),
    CountryInfo("SZ", ContinentRegion.AFRICA, "SZL"),
    CountryInfo("KE", ContinentRegion.AFRICA, "KES"),
    CountryInfo("TZ", ContinentRegion.AFRICA, "TZS"),
    CountryInfo("UG", ContinentRegion.AFRICA, "UGX"),
    CountryInfo("RW", ContinentRegion.AFRICA, "RWF"),
    CountryInfo("BI", ContinentRegion.AFRICA, "BIF"),
    CountryInfo("ET", ContinentRegion.AFRICA, "ETB"),
    CountryInfo("ER", ContinentRegion.AFRICA, "ERN"),
    CountryInfo("DJ", ContinentRegion.AFRICA, "DJF"),
    CountryInfo("SO", ContinentRegion.AFRICA, "SOS"),
    CountryInfo("BF", ContinentRegion.AFRICA, "XOF"),
    CountryInfo("CV", ContinentRegion.AFRICA, "CVE"),
    CountryInfo("ST", ContinentRegion.AFRICA, "STN"),
    CountryInfo("SC", ContinentRegion.AFRICA, "SCR"),
    CountryInfo("MU", ContinentRegion.AFRICA, "MUR"),
    CountryInfo("MG", ContinentRegion.AFRICA, "MGA"),
    CountryInfo("KM", ContinentRegion.AFRICA, "KMF"),
    CountryInfo("FR", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("ES", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("DE", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("IT", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("PT", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("NL", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("BE", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("LU", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("GB", ContinentRegion.EUROPE, "GBP"),
    CountryInfo("IE", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("CH", ContinentRegion.EUROPE, "CHF"),
    CountryInfo("AT", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("SE", ContinentRegion.EUROPE, "SEK"),
    CountryInfo("NO", ContinentRegion.EUROPE, "NOK"),
    CountryInfo("DK", ContinentRegion.EUROPE, "DKK"),
    CountryInfo("FI", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("IS", ContinentRegion.EUROPE, "ISK"),
    CountryInfo("PL", ContinentRegion.EUROPE, "PLN"),
    CountryInfo("CZ", ContinentRegion.EUROPE, "CZK"),
    CountryInfo("SK", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("HU", ContinentRegion.EUROPE, "HUF"),
    CountryInfo("RO", ContinentRegion.EUROPE, "RON"),
    CountryInfo("BG", ContinentRegion.EUROPE, "BGN"),
    CountryInfo("GR", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("HR", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("SI", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("RS", ContinentRegion.EUROPE, "RSD"),
    CountryInfo("BA", ContinentRegion.EUROPE, "BAM"),
    CountryInfo("ME", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("MK", ContinentRegion.EUROPE, "MKD"),
    CountryInfo("AL", ContinentRegion.EUROPE, "ALL"),
    CountryInfo("XK", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("LT", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("LV", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("EE", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("MD", ContinentRegion.EUROPE, "MDL"),
    CountryInfo("UA", ContinentRegion.EUROPE, "UAH"),
    CountryInfo("BY", ContinentRegion.EUROPE, "BYN"),
    CountryInfo("RU", ContinentRegion.EUROPE, "RUB"),
    CountryInfo("MT", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("CY", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("AD", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("MC", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("LI", ContinentRegion.EUROPE, "CHF"),
    CountryInfo("SM", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("VA", ContinentRegion.EUROPE, "EUR"),
    CountryInfo("TR", ContinentRegion.ASIA, "TRY"),
    CountryInfo("IL", ContinentRegion.ASIA, "ILS"),
    CountryInfo("PS", ContinentRegion.ASIA, "ILS"),
    CountryInfo("JO", ContinentRegion.ASIA, "JOD"),
    CountryInfo("LB", ContinentRegion.ASIA, "LBP"),
    CountryInfo("SY", ContinentRegion.ASIA, "SYP"),
    CountryInfo("IQ", ContinentRegion.ASIA, "IQD"),
    CountryInfo("SA", ContinentRegion.ASIA, "SAR"),
    CountryInfo("YE", ContinentRegion.ASIA, "YER"),
    CountryInfo("OM", ContinentRegion.ASIA, "OMR"),
    CountryInfo("AE", ContinentRegion.ASIA, "AED"),
    CountryInfo("QA", ContinentRegion.ASIA, "QAR"),
    CountryInfo("BH", ContinentRegion.ASIA, "BHD"),
    CountryInfo("KW", ContinentRegion.ASIA, "KWD"),
    CountryInfo("IR", ContinentRegion.ASIA, "IRR"),
    CountryInfo("AF", ContinentRegion.ASIA, "AFN"),
    CountryInfo("PK", ContinentRegion.ASIA, "PKR"),
    CountryInfo("IN", ContinentRegion.ASIA, "INR"),
    CountryInfo("BD", ContinentRegion.ASIA, "BDT"),
    CountryInfo("LK", ContinentRegion.ASIA, "LKR"),
    CountryInfo("NP", ContinentRegion.ASIA, "NPR"),
    CountryInfo("BT", ContinentRegion.ASIA, "BTN"),
    CountryInfo("MM", ContinentRegion.ASIA, "MMK"),
    CountryInfo("TH", ContinentRegion.ASIA, "THB"),
    CountryInfo("LA", ContinentRegion.ASIA, "LAK"),
    CountryInfo("KH", ContinentRegion.ASIA, "KHR"),
    CountryInfo("VN", ContinentRegion.ASIA, "VND"),
    CountryInfo("MY", ContinentRegion.ASIA, "MYR"),
    CountryInfo("SG", ContinentRegion.ASIA, "SGD"),
    CountryInfo("ID", ContinentRegion.ASIA, "IDR"),
    CountryInfo("PH", ContinentRegion.ASIA, "PHP"),
    CountryInfo("BN", ContinentRegion.ASIA, "BND"),
    CountryInfo("TL", ContinentRegion.ASIA, "USD"),
    CountryInfo("CN", ContinentRegion.ASIA, "CNY"),
    CountryInfo("JP", ContinentRegion.ASIA, "JPY"),
    CountryInfo("KR", ContinentRegion.ASIA, "KRW"),
    CountryInfo("KP", ContinentRegion.ASIA, "KPW"),
    CountryInfo("MN", ContinentRegion.ASIA, "MNT"),
    CountryInfo("TW", ContinentRegion.ASIA, "TWD"),
    CountryInfo("HK", ContinentRegion.ASIA, "HKD"),
    CountryInfo("MO", ContinentRegion.ASIA, "MOP"),
    CountryInfo("KZ", ContinentRegion.ASIA, "KZT"),
    CountryInfo("UZ", ContinentRegion.ASIA, "UZS"),
    CountryInfo("TM", ContinentRegion.ASIA, "TMT"),
    CountryInfo("TJ", ContinentRegion.ASIA, "TJS"),
    CountryInfo("KG", ContinentRegion.ASIA, "KGS"),
    CountryInfo("AM", ContinentRegion.ASIA, "AMD"),
    CountryInfo("AZ", ContinentRegion.ASIA, "AZN"),
    CountryInfo("GE", ContinentRegion.ASIA, "GEL"),
    CountryInfo("MV", ContinentRegion.ASIA, "MVR"),
    CountryInfo("US", ContinentRegion.NORTH_AMERICA, "USD"),
    CountryInfo("CA", ContinentRegion.NORTH_AMERICA, "CAD"),
    CountryInfo("MX", ContinentRegion.NORTH_AMERICA, "MXN"),
    CountryInfo("GT", ContinentRegion.NORTH_AMERICA, "GTQ"),
    CountryInfo("BZ", ContinentRegion.NORTH_AMERICA, "BZD"),
    CountryInfo("SV", ContinentRegion.NORTH_AMERICA, "USD"),
    CountryInfo("HN", ContinentRegion.NORTH_AMERICA, "HNL"),
    CountryInfo("NI", ContinentRegion.NORTH_AMERICA, "NIO"),
    CountryInfo("CR", ContinentRegion.NORTH_AMERICA, "CRC"),
    CountryInfo("PA", ContinentRegion.NORTH_AMERICA, "PAB"),
    CountryInfo("CU", ContinentRegion.NORTH_AMERICA, "CUP"),
    CountryInfo("JM", ContinentRegion.NORTH_AMERICA, "JMD"),
    CountryInfo("HT", ContinentRegion.NORTH_AMERICA, "HTG"),
    CountryInfo("DO", ContinentRegion.NORTH_AMERICA, "DOP"),
    CountryInfo("BS", ContinentRegion.NORTH_AMERICA, "BSD"),
    CountryInfo("BB", ContinentRegion.NORTH_AMERICA, "BBD"),
    CountryInfo("TT", ContinentRegion.NORTH_AMERICA, "TTD"),
    CountryInfo("GD", ContinentRegion.NORTH_AMERICA, "XCD"),
    CountryInfo("LC", ContinentRegion.NORTH_AMERICA, "XCD"),
    CountryInfo("VC", ContinentRegion.NORTH_AMERICA, "XCD"),
    CountryInfo("AG", ContinentRegion.NORTH_AMERICA, "XCD"),
    CountryInfo("DM", ContinentRegion.NORTH_AMERICA, "XCD"),
    CountryInfo("KN", ContinentRegion.NORTH_AMERICA, "XCD"),
    CountryInfo("BR", ContinentRegion.SOUTH_AMERICA, "BRL"),
    CountryInfo("AR", ContinentRegion.SOUTH_AMERICA, "ARS"),
    CountryInfo("CL", ContinentRegion.SOUTH_AMERICA, "CLP"),
    CountryInfo("CO", ContinentRegion.SOUTH_AMERICA, "COP"),
    CountryInfo("PE", ContinentRegion.SOUTH_AMERICA, "PEN"),
    CountryInfo("VE", ContinentRegion.SOUTH_AMERICA, "VES"),
    CountryInfo("EC", ContinentRegion.SOUTH_AMERICA, "USD"),
    CountryInfo("BO", ContinentRegion.SOUTH_AMERICA, "BOB"),
    CountryInfo("PY", ContinentRegion.SOUTH_AMERICA, "PYG"),
    CountryInfo("UY", ContinentRegion.SOUTH_AMERICA, "UYU"),
    CountryInfo("GY", ContinentRegion.SOUTH_AMERICA, "GYD"),
    CountryInfo("SR", ContinentRegion.SOUTH_AMERICA, "SRD"),
    CountryInfo("AU", ContinentRegion.OCEANIA, "AUD"),
    CountryInfo("NZ", ContinentRegion.OCEANIA, "NZD"),
    CountryInfo("FJ", ContinentRegion.OCEANIA, "FJD"),
    CountryInfo("PG", ContinentRegion.OCEANIA, "PGK"),
    CountryInfo("SB", ContinentRegion.OCEANIA, "SBD"),
    CountryInfo("VU", ContinentRegion.OCEANIA, "VUV"),
    CountryInfo("WS", ContinentRegion.OCEANIA, "WST"),
    CountryInfo("TO", ContinentRegion.OCEANIA, "TOP"),
)

private val COUNTRY_BY_CODE: Map<String, CountryInfo> = COUNTRIES.associateBy { it.code }

fun currencyForCountry(code: String): String = COUNTRY_BY_CODE[code]?.currency ?: "USD"

fun isKnownCountry(code: String): Boolean = COUNTRY_BY_CODE.containsKey(code)

/** i18n key for a continent group's label in a country picker, e.g.
 * "deposer.region_europe" — shared by every country picker (deposer-annonce,
 * the app-wide country switcher) so the mapping lives in exactly one place. */
fun regionLabelKey(region: ContinentRegion): String = "deposer.region_${region.name.lowercase()}"

/** Groups the full country list into continents for pickers — Morocco
 * pinned first as the platform's home market, then continents in a fixed,
 * stable order (mirrors web's COUNTRY_REGIONS). */
val COUNTRY_REGIONS: List<Pair<ContinentRegion, List<String>>> = listOf(
    ContinentRegion.MOROCCO, ContinentRegion.AFRICA, ContinentRegion.EUROPE, ContinentRegion.ASIA,
    ContinentRegion.NORTH_AMERICA, ContinentRegion.SOUTH_AMERICA, ContinentRegion.OCEANIA
).map { region -> region to COUNTRIES.filter { it.region == region }.map { it.code } }

/** Flag emoji computed from the ISO alpha-2 code (regional indicator
 * symbols) — no per-country emoji table to maintain. Unlike the web app,
 * Android renders these natively via Noto Color Emoji with no known
 * rendering bug, so (unlike web's FlagIconComponent/bundled SVGs) a plain
 * computed emoji is the pragmatic, already-proven approach here (see
 * I18nRepository.SUPPORTED_LANGUAGES's language-flag emoji). */
fun countryFlag(code: String): String =
    code.uppercase().map { 0x1F1E6 - 'A'.code + it.code }.joinToString("") { String(Character.toChars(it)) }

/** Major/mid-size cities for the ~30 countries curated in an earlier round
 * (moved here 1:1 from web's CITIES_BY_COUNTRY). Every other country in
 * COUNTRIES has no entry here on purpose — the city field falls back to
 * free text for those, exactly like web's CountrySelectComponent. */
val CITIES_BY_COUNTRY: Map<String, List<String>> = mapOf(
    "FR" to listOf("Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Étienne", "Toulon", "Grenoble", "Dijon", "Angers", "Nîmes", "Villeurbanne", "Clermont-Ferrand", "Le Mans", "Aix-en-Provence", "Brest", "Tours", "Limoges", "Amiens", "Annecy", "Perpignan", "Besançon", "Metz", "Orléans", "Rouen", "Mulhouse", "Caen", "Nancy", "Argenteuil", "Saint-Denis", "Roubaix", "Tourcoing", "Avignon", "Créteil", "Poitiers", "Versailles", "Pau", "La Rochelle", "Calais", "Cannes", "Antibes", "Béziers"),
    "ES" to listOf("Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Malaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón", "Vitoria-Gasteiz", "A Coruña", "Granada", "Elche", "Oviedo", "Badalona", "Cartagena", "Terrassa", "Jerez de la Frontera", "Sabadell", "Móstoles", "Alcalá de Henares", "Pamplona", "Fuenlabrada", "Almería", "San Sebastián", "Leganés", "Santander", "Burgos", "Castellón de la Plana", "Getafe", "Albacete", "Alcorcón", "Logroño", "Badajoz", "Salamanca", "Huelva", "Marbella", "Tarragona", "León", "Cádiz", "Lleida", "Dos Hermanas", "Mataró", "Santa Cruz de Tenerife"),
    "DE" to listOf("Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hannover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Mannheim", "Karlsruhe", "Augsburg", "Wiesbaden", "Mönchengladbach", "Gelsenkirchen", "Braunschweig", "Chemnitz", "Kiel", "Aachen", "Halle", "Magdeburg", "Freiburg", "Krefeld", "Lübeck", "Oberhausen", "Erfurt", "Mainz", "Rostock", "Kassel", "Hagen", "Saarbrücken", "Hamm", "Potsdam", "Ludwigshafen", "Oldenburg", "Leverkusen", "Osnabrück", "Solingen", "Heidelberg"),
    "IT" to listOf("Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste", "Taranto", "Brescia", "Parma", "Prato", "Modena", "Reggio Calabria", "Reggio Emilia", "Perugia", "Ravenna", "Livorno", "Cagliari", "Foggia", "Rimini", "Salerno", "Ferrara", "Sassari", "Latina", "Monza", "Syracuse", "Pescara", "Bergamo", "Trento", "Forlì", "Vicenza", "Terni", "Bolzano", "Novara", "Piacenza", "Ancona", "Andria", "Arezzo", "Udine", "Cesena", "Lecce", "La Spezia"),
    "PT" to listOf("Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal", "Coimbra", "Setúbal", "Almada", "Agualva-Cacém", "Queluz", "Barreiro", "Aveiro", "Faro", "Évora", "Viseu", "Guimarães", "Leiria", "Portimão", "Odivelas", "Barcelos", "Póvoa de Varzim", "Rio Maior", "Viana do Castelo", "Vila Real", "Covilhã", "Tomar", "Torres Vedras", "Peniche", "Elvas", "Beja", "Chaves", "Estoril", "Cascais", "Sintra", "Loures", "Matosinhos"),
    "NL" to listOf("Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen", "Enschede", "Haarlem", "Arnhem", "Zaanstad", "Amersfoort", "Apeldoorn", "Hoofddorp", "Maastricht", "Leiden", "Dordrecht", "Zoetermeer", "Zwolle", "Deventer", "Delft", "Alkmaar", "Heerlen", "Venlo", "Leeuwarden", "Hilversum", "Amstelveen", "Purmerend", "Roosendaal", "Oss", "Schiedam", "Spijkenisse", "Vlaardingen", "Almelo", "Gouda", "Hengelo", "Emmen"),
    "BE" to listOf("Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Aalst", "Mechelen", "La Louvière", "Kortrijk", "Hasselt", "Sint-Niklaas", "Ostend", "Tournai", "Genk", "Seraing", "Roeselare", "Verviers", "Mouscron", "Beveren", "Dendermonde", "Beringen", "Turnhout", "Dilbeek", "Heist-op-den-Berg", "Lokeren", "Vilvoorde"),
    "GB" to listOf("London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Sheffield", "Edinburgh", "Bristol", "Cardiff", "Leicester", "Belfast", "Nottingham", "Newcastle upon Tyne", "Southampton", "Portsmouth", "Bradford", "Coventry", "Kingston upon Hull", "Stoke-on-Trent", "Wolverhampton", "Plymouth", "Derby", "Swansea", "Aberdeen", "Reading", "Milton Keynes", "Northampton", "Norwich", "Luton", "York", "Oxford", "Cambridge", "Preston", "Sunderland", "Middlesbrough", "Blackpool", "Bolton", "Ipswich", "Watford", "Slough", "Exeter", "Gloucester", "Dundee", "Blackburn", "Southend-on-Sea", "Peterborough", "Bath", "Brighton", "Warrington"),
    "CH" to listOf("Zurich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel/Bienne", "Thun", "Köniz", "La Chaux-de-Fonds", "Fribourg", "Schaffhausen", "Chur", "Vernier", "Neuchâtel", "Uster", "Sion", "Emmen", "Zug", "Yverdon-les-Bains", "Kriens", "Rapperswil-Jona", "Dübendorf", "Montreux", "Dietikon", "Frauenfeld", "Wetzikon"),
    "AT" to listOf("Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn", "Wiener Neustadt", "Steyr", "Feldkirch", "Bregenz", "Leonding", "Klosterneuburg", "Baden", "Wolfsberg", "Leoben", "Krems an der Donau", "Traun", "Amstetten", "Lustenau", "Kapfenberg", "Hallein"),
    "SE" to listOf("Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping", "Lund", "Umeå", "Gävle", "Borås", "Södertälje", "Eskilstuna", "Halmstad", "Växjö", "Karlstad", "Sundsvall", "Trollhättan", "Östersund", "Borlänge", "Falun", "Kalmar"),
    "PL" to listOf("Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Białystok", "Katowice", "Gdynia", "Częstochowa", "Radom", "Sosnowiec", "Toruń", "Kielce", "Gliwice", "Zabrze", "Bytom", "Olsztyn", "Bielsko-Biała", "Rzeszów", "Ruda Śląska", "Rybnik", "Tychy", "Opole", "Gorzów Wielkopolski", "Płock", "Wałbrzych", "Włocławek", "Elbląg", "Zielona Góra", "Koszalin"),
    "GR" to listOf("Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Rhodes", "Ioannina", "Chania", "Chalcis", "Agrinio", "Katerini", "Trikala", "Serres", "Lamia", "Alexandroupoli", "Xanthi", "Kavala", "Kalamata", "Kozani", "Veroia", "Drama", "Komotini", "Rethymno", "Karditsa"),
    "IE" to listOf("Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan", "Kilkenny", "Ennis", "Carlow", "Tralee", "Naas", "Sligo", "Athlone", "Wexford", "Letterkenny", "Celbridge"),
    "DK" to listOf("Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Silkeborg", "Næstved", "Fredericia", "Viborg", "Køge", "Holstebro", "Taastrup", "Slagelse", "Hillerød"),
    "DZ" to listOf("Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Djelfa", "Sétif", "Sidi Bel Abbès", "Biskra", "Tébessa", "Tlemcen", "Béjaïa", "Skikda", "Tiaret", "Ouargla", "Bordj Bou Arréridj", "Béchar", "Mostaganem", "Chlef", "Médéa", "El Oued", "Relizane", "Tizi Ouzou", "M'Sila", "Mascara", "Ghardaïa", "Souk Ahras", "Jijel", "Saïda"),
    "TN" to listOf("Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès", "Ariana", "Gafsa", "Monastir", "Ben Arous", "Kasserine", "Médenine", "Nabeul", "Tataouine", "Béja", "Jendouba", "Mahdia", "Sidi Bouzid", "Tozeur", "Zaghouan", "Siliana", "Kef", "Manouba"),
    "LY" to listOf("Tripoli", "Benghazi", "Misrata", "Zawiya", "Bayda", "Zliten", "Ajdabiya", "Tobruk", "Sabha", "Sirte", "Derna", "Khoms"),
    "MR" to listOf("Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso", "Zouérat", "Atar", "Néma", "Sélibaby", "Aleg", "Akjoujt"),
    "SN" to listOf("Dakar", "Touba", "Thiès", "Kaolack", "M'bour", "Ziguinchor", "Diourbel", "Saint-Louis", "Louga", "Tambacounda", "Kolda", "Rufisque", "Mbacké", "Richard Toll", "Kaffrine", "Fatick", "Kédougou"),
    "ML" to listOf("Bamako", "Sikasso", "Mopti", "Koutiala", "Ségou", "Kayes", "Gao", "Kati", "San", "Timbuktu", "Kolondiéba", "Bougouni", "Koulikoro"),
    "EG" to listOf("Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "El Mahalla El Kubra", "Tanta", "Asyut", "Ismailia", "Faiyum", "Zagazig", "Aswan", "Damietta", "Damanhur", "Minya", "Beni Suef", "Qena", "Sohag", "Hurghada", "6th of October City", "Shibin El Kom", "Banha"),
    "NG" to listOf("Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin", "Oyo", "Enugu", "Abeokuta", "Kaduna", "Onitsha", "Warri", "Sokoto", "Calabar", "Katsina", "Akure", "Bauchi", "Owerri", "Uyo", "Ado-Ekiti"),
    "CI" to listOf("Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "Korhogo", "San-Pédro", "Man", "Divo", "Gagnoa", "Anyama", "Abengourou", "Agboville", "Grand-Bassam", "Dabou", "Bondoukou", "Séguéla"),
    "GH" to listOf("Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Sunyani", "Cape Coast", "Obuasi", "Teshie", "Tema", "Koforidua", "Ho", "Wa", "Bolgatanga", "Techiman", "Nkawkaw"),
    "CM" to listOf("Douala", "Yaoundé", "Garoua", "Bamenda", "Maroua", "Bafoussam", "Ngaoundéré", "Bertoua", "Loum", "Kumba", "Nkongsamba", "Buea", "Edéa", "Kribi", "Ebolowa"),
    "ZA" to listOf("Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "Nelspruit", "Kimberley", "Polokwane", "Pietermaritzburg", "Rustenburg", "George", "Welkom", "East London", "Vereeniging", "Klerksdorp", "Potchefstroom", "Vryburg", "Upington", "Worcester"),
    "KE" to listOf("Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Kakamega", "Nyeri", "Machakos", "Meru", "Kericho", "Embu"),
    "ET" to listOf("Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Adama", "Hawassa", "Bahir Dar", "Jimma", "Jijiga", "Dessie", "Shashamane", "Bishoftu", "Sodo", "Arba Minch", "Hosaena"),
    "TZ" to listOf("Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya", "Morogoro", "Tanga", "Kahama", "Tabora", "Zanzibar City", "Kigoma", "Sumbawanga", "Kasulu", "Songea", "Musoma"),
    "SD" to listOf("Khartoum", "Omdurman", "Nyala", "Port Sudan", "Kassala", "El Obeid", "Wad Madani", "El Fasher", "Gedaref", "Kosti", "Atbara", "Dongola", "Sennar", "Nahud", "El Daein"),
    "SS" to listOf("Juba", "Wau", "Malakal", "Yei", "Aweil", "Bor", "Yambio", "Bentiu", "Rumbek", "Torit"),
    "NE" to listOf("Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Tillabéri", "Diffa", "Arlit", "Birni-N'Konni"),
    "TD" to listOf("N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo"),
    "GM" to listOf("Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Sukuta", "Basse Santa Su", "Gunjur", "Soma"),
    "GW" to listOf("Bissau", "Bafatá", "Gabú", "Bissorã", "Bolama", "Cacheu", "Catió", "Farim", "Mansôa", "Buba"),
    "GN" to listOf("Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Mamou", "Boké", "Faranah", "Kissidougou", "Siguiri"),
    "SL" to listOf("Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Waterloo", "Lunsar", "Port Loko", "Kabala", "Magburaka"),
    "LR" to listOf("Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama", "Buchanan", "Zwedru", "Ganta", "Robertsport"),
    "TG" to listOf("Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Dapaong", "Tsévié", "Aného", "Mango", "Bassar"),
    "BJ" to listOf("Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Kandi", "Abomey", "Natitingou", "Lokossa", "Ouidah"),
    "CF" to listOf("Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar", "Bossangoa", "Bria", "Bangassou", "Nola"),
    "GQ" to listOf("Malabo", "Bata", "Ebebiyín", "Aconibe", "Añisoc", "Luba", "Evinayong", "Mongomo", "Mengomeyén", "Micomeseng"),
    "GA" to listOf("Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Lambaréné", "Tchibanga", "Koulamoutou", "Makokou"),
    "CG" to listOf("Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Ouesso", "Impfondo", "Madingou", "Owando", "Sibiti", "Gamboma"),
    "CD" to listOf("Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu", "Goma", "Kolwezi", "Likasi", "Tshikapa", "Uvira", "Matadi", "Mbandaka", "Kikwit", "Bunia"),
    "AO" to listOf("Luanda", "Huambo", "Lobito", "Benguela", "Kuito", "Lubango", "Malanje", "Namibe", "Soyo", "Cabinda", "Uíge", "Saurimo"),
    "ZM" to listOf("Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya", "Kasama", "Chipata"),
    "MW" to listOf("Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Karonga", "Salima", "Nkhotakota", "Balaka"),
    "MZ" to listOf("Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete", "Xai-Xai", "Lichinga", "Pemba"),
    "ZW" to listOf("Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Epworth", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi", "Marondera"),
    "BW" to listOf("Gaborone", "Francistown", "Molepolole", "Selebi-Phikwe", "Maun", "Serowe", "Kanye", "Mahalapye", "Mochudi", "Mogoditshane"),
    "NA" to listOf("Windhoek", "Rundu", "Walvis Bay", "Swakopmund", "Oshakati", "Rehoboth", "Katima Mulilo", "Otjiwarongo", "Okahandja", "Gobabis"),
    "LS" to listOf("Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Maputsoe", "Mohale's Hoek", "Quthing", "Qacha's Nek", "Butha-Buthe", "Mokhotlong"),
    "SZ" to listOf("Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano", "Piggs Peak", "Siteki", "Hlatikulu", "Lobamba", "Simunye"),
    "UG" to listOf("Kampala", "Nansana", "Kira", "Ssabagabo", "Mbarara", "Mukono", "Gulu", "Lira", "Mbale", "Jinja", "Kasese", "Masaka"),
    "RW" to listOf("Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba", "Cyangugu", "Kibungo", "Kibuye", "Nyanza"),
    "BI" to listOf("Bujumbura", "Gitega", "Muyinga", "Ruyigi", "Ngozi", "Kayanza", "Rumonge", "Bururi", "Cibitoke", "Muramvya"),
    "ER" to listOf("Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Barentu", "Adi Keyh", "Dekemhare", "Ghinda", "Nakfa"),
    "DJ" to listOf("Djibouti City", "Ali Sabieh", "Tadjourah", "Obock", "Dikhil", "Arta", "Holhol", "Yoboki", "Balho", "Randa"),
    "SO" to listOf("Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Merca", "Berbera", "Baidoa", "Galkayo", "Jowhar", "Beledweyne"),
    "BF" to listOf("Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Kaya", "Tenkodogo", "Fada N'Gourma", "Dédougou", "Houndé"),
    "CV" to listOf("Praia", "Mindelo", "Santa Maria", "Espargos", "Assomada", "Pedra Badejo", "Tarrafal", "Porto Novo", "São Filipe", "Sal Rei"),
    "ST" to listOf("São Tomé", "Santo António", "Neves", "Santana", "Trindade", "Guadalupe", "Santo Amaro", "São João dos Angolares", "Porto Alegre", "Pantufo"),
    "SC" to listOf("Victoria", "Anse Boileau", "Beau Vallon", "Anse Royale", "Takamaka", "Cascade", "Grand Anse", "Bel Ombre", "Port Glaud", "Baie Lazare"),
    "MU" to listOf("Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Triolet", "Goodlands", "Centre de Flacq", "Bel Air", "Mahébourg"),
    "MG" to listOf("Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Antsiranana", "Ambovombe", "Morondava", "Ambatondrazaka"),
    "KM" to listOf("Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeo", "Mitsamiouli", "Ouani", "Sima", "Mramani", "Foumbouni"),
    "LU" to listOf("Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck", "Diekirch", "Wiltz", "Echternach", "Rumelange", "Grevenmacher"),
    "NO" to listOf("Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg", "Skien", "Ålesund", "Bodø", "Sandefjord", "Haugesund"),
    "FI" to listOf("Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori", "Kouvola", "Joensuu", "Lappeenranta", "Vaasa", "Rovaniemi"),
    "IS" to listOf("Reykjavík", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær", "Garðabær", "Mosfellsbær", "Árborg", "Akranes", "Fjarðabyggð"),
    "CZ" to listOf("Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Ústí nad Labem", "České Budějovice", "Hradec Králové", "Pardubice", "Zlín", "Havířov", "Kladno", "Most"),
    "SK" to listOf("Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava", "Martin", "Trenčín", "Poprad"),
    "HU" to listOf("Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr", "Nyíregyháza", "Kecskemét", "Székesfehérvár", "Szombathely"),
    "RO" to listOf("Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea", "Brăila", "Arad", "Sibiu", "Bacău"),
    "BG" to listOf("Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen"),
    "HR" to listOf("Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula", "Karlovac", "Sisak", "Varaždin"),
    "SI" to listOf("Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik"),
    "RS" to listOf("Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo", "Čačak", "Kruševac", "Kraljevo"),
    "BA" to listOf("Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina", "Brčko", "Prijedor", "Trebinje", "Doboj"),
    "ME" to listOf("Podgorica", "Nikšić", "Herceg Novi", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar", "Budva", "Kotor", "Berane"),
    "MK" to listOf("Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Štip", "Ohrid", "Gostivar", "Strumica"),
    "AL" to listOf("Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Korçë", "Berat", "Lushnjë", "Kavajë"),
    "XK" to listOf("Pristina", "Prizren", "Ferizaj", "Peja", "Gjakova", "Gjilan", "Mitrovica", "Podujeva", "Vushtrri", "Suhareka"),
    "LT" to listOf("Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Mažeikiai", "Jonava", "Utena"),
    "LV" to listOf("Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils", "Rēzekne", "Valmiera", "Jēkabpils", "Ogre"),
    "EE" to listOf("Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi", "Rakvere", "Maardu", "Kuressaare", "Sillamäe"),
    "MD" to listOf("Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul", "Ungheni", "Soroca", "Orhei", "Comrat"),
    "UA" to listOf("Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol", "Vinnytsia", "Chernihiv"),
    "BY" to listOf("Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Babruysk", "Baranovichi", "Borisov", "Pinsk"),
    "RU" to listOf("Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd"),
    "MT" to listOf("Valletta", "Birkirkara", "Mosta", "Qormi", "Żabbar", "San Pawl il-Baħar", "Sliema", "Żejtun", "Fgura", "Rabat"),
    "CY" to listOf("Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos", "Kyrenia", "Paralimni", "Aradippou", "Strovolos", "Lakatamia"),
    "AD" to listOf("Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana", "Santa Coloma", "Ordino", "Canillo", "Pas de la Casa", "Arinsal"),
    "MC" to listOf("Monaco-Ville", "Monte Carlo", "La Condamine", "Fontvieille", "Moneghetti", "Larvotto", "Saint Roman", "La Rousse", "Les Révoires", "Le Portier"),
    "LI" to listOf("Vaduz", "Schaan", "Triesen", "Balzers", "Eschen", "Mauren", "Triesenberg", "Ruggell", "Gamprin", "Schellenberg"),
    "SM" to listOf("San Marino City", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino", "Acquaviva", "Faetano", "Montegiardino", "Chiesanuova", "San Giovanni"),
    "VA" to listOf("Vatican City"),
    "TR" to listOf("Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Şanlıurfa", "Kayseri", "Mersin", "Eskişehir", "Diyarbakır", "Samsun", "Denizli"),
    "IL" to listOf("Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beersheba", "Bnei Brak", "Holon"),
    "PS" to listOf("Gaza", "Ramallah", "Hebron", "Nablus", "Bethlehem", "Khan Yunis", "Jenin", "Rafah", "Tulkarm", "Qalqilya"),
    "JO" to listOf("Amman", "Zarqa", "Irbid", "Russeifa", "Aqaba", "Salt", "Madaba", "Mafraq", "Karak", "Jerash"),
    "LB" to listOf("Beirut", "Tripoli", "Sidon", "Tyre", "Zahlé", "Baalbek", "Byblos", "Jounieh", "Batroun", "Nabatieh"),
    "SY" to listOf("Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor", "Raqqa", "Daraa", "Tartus", "Idlib"),
    "IQ" to listOf("Baghdad", "Basra", "Mosul", "Erbil", "Najaf", "Karbala", "Kirkuk", "Sulaymaniyah", "Nasiriyah", "Amara"),
    "SA" to listOf("Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Taif", "Tabuk", "Buraidah", "Khamis Mushait", "Hail", "Najran"),
    "YE" to listOf("Sanaa", "Aden", "Taiz", "Hodeidah", "Ibb", "Mukalla", "Dhamar", "Amran", "Sayyan", "Zinjibar"),
    "OM" to listOf("Muscat", "Seeb", "Salalah", "Bawshar", "Sohar", "Sur", "Nizwa", "Ibri", "Rustaq", "Buraimi"),
    "AE" to listOf("Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Khor Fakkan", "Kalba"),
    "QA" to listOf("Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal", "Al Shamal", "Mesaieed", "Dukhan", "Al Daayen", "Lusail"),
    "BH" to listOf("Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Al Malikiyah"),
    "KW" to listOf("Kuwait City", "Al Ahmadi", "Hawalli", "As Salimiyah", "Sabah as Salim", "Al Farwaniyah", "Al Jahra", "Al Fintas", "Al Fahahil", "Mangaf"),
    "IR" to listOf("Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Kermanshah", "Urmia", "Rasht", "Zahedan"),
    "AF" to listOf("Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Kunduz", "Jalalabad", "Lashkar Gah", "Taloqan", "Puli Khumri", "Ghazni"),
    "PK" to listOf("Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Hyderabad", "Gujranwala", "Peshawar", "Islamabad", "Quetta", "Sialkot", "Bahawalpur"),
    "IN" to listOf("Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Bhopal", "Patna", "Vadodara", "Ghaziabad"),
    "BD" to listOf("Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Comilla", "Rangpur", "Mymensingh", "Barisal", "Gazipur"),
    "LK" to listOf("Colombo", "Dehiwala-Mount Lavinia", "Kandy", "Galle", "Jaffna", "Negombo", "Trincomalee", "Batticaloa", "Anuradhapura", "Matara"),
    "NP" to listOf("Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur", "Birgunj", "Dharan", "Butwal", "Hetauda", "Janakpur"),
    "BT" to listOf("Thimphu", "Phuntsholing", "Punakha", "Paro", "Gelephu", "Samdrup Jongkhar", "Wangdue Phodrang", "Trashigang", "Jakar", "Trongsa"),
    "MM" to listOf("Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago", "Pathein", "Monywa", "Meiktila", "Myitkyina", "Taunggyi"),
    "TH" to listOf("Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai", "Udon Thani", "Pak Kret", "Khon Kaen", "Rayong", "Surat Thani"),
    "LA" to listOf("Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Xam Neua", "Thakhek", "Muang Xay", "Vang Vieng", "Attapeu", "Phonsavan"),
    "KH" to listOf("Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet", "Kampong Cham", "Ta Khmau", "Pursat", "Kampot", "Kratie"),
    "VN" to listOf("Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Bien Hoa", "Hue", "Nha Trang", "Buon Ma Thuot", "Vung Tau"),
    "MY" to listOf("Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Johor Bahru", "Malacca City", "Kota Kinabalu", "Kuching", "Seremban"),
    "SG" to listOf("Singapore", "Jurong West", "Woodlands", "Tampines", "Sengkang", "Hougang", "Yishun", "Bedok", "Punggol", "Ang Mo Kio"),
    "ID" to listOf("Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Palembang", "Depok", "Tangerang", "Bekasi", "Bogor", "Batam", "Denpasar", "Yogyakarta"),
    "PH" to listOf("Manila", "Quezon City", "Davao City", "Caloocan", "Cebu City", "Zamboanga City", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro"),
    "BN" to listOf("Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Muara", "Jerudong", "Lumut", "Sengkurong", "Tanjong Bunut"),
    "TL" to listOf("Dili", "Baucau", "Maliana", "Suai", "Liquiçá", "Aileu", "Ainaro", "Same", "Los Palos", "Viqueque"),
    "CN" to listOf("Shanghai", "Beijing", "Chongqing", "Guangzhou", "Shenzhen", "Chengdu", "Tianjin", "Wuhan", "Xi'an", "Hangzhou", "Nanjing", "Shenyang", "Qingdao", "Dalian", "Zhengzhou", "Harbin", "Kunming", "Xiamen"),
    "JP" to listOf("Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Chiba", "Kitakyushu"),
    "KR" to listOf("Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang"),
    "KP" to listOf("Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju", "Tanchon", "Kaesong", "Sariwon", "Hyesan"),
    "MN" to listOf("Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Nalaikh", "Khovd", "Ölgii", "Baganuur", "Sükhbaatar"),
    "TW" to listOf("Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan", "Hsinchu", "Keelung", "Chiayi", "Changhua", "Yunlin"),
    "HK" to listOf("Hong Kong Island", "Kowloon", "Tsuen Wan", "Sha Tin", "Tuen Mun", "Yuen Long", "Tai Po", "Sai Kung", "North Point", "Kwun Tong"),
    "MO" to listOf("Macau", "Taipa", "Coloane", "Cotai"),
    "KZ" to listOf("Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Ust-Kamenogorsk", "Semey", "Atyrau"),
    "UZ" to listOf("Tashkent", "Namangan", "Samarkand", "Andijan", "Nukus", "Bukhara", "Qarshi", "Fergana", "Jizzakh", "Termez"),
    "TM" to listOf("Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat", "Bayramaly", "Tejen", "Serdar", "Abadan", "Baýramaly"),
    "TJ" to listOf("Dushanbe", "Khujand", "Kulob", "Bokhtar", "Istaravshan", "Konibodom", "Tursunzoda", "Panjakent", "Vahdat", "Isfara"),
    "KG" to listOf("Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Kara-Balta", "Naryn", "Talas", "Batken", "Uzgen"),
    "AM" to listOf("Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan", "Kapan", "Hrazdan", "Armavir", "Artashat", "Ijevan"),
    "AZ" to listOf("Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Shirvan", "Nakhchivan", "Shaki", "Yevlakh", "Khankendi"),
    "GE" to listOf("Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Zugdidi", "Gori", "Poti", "Samtredia", "Khashuri", "Senaki"),
    "MV" to listOf("Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo", "Naifaru", "Hithadhoo", "Dhidhdhoo", "Eydhafushi", "Funadhoo"),
    "US" to listOf("New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "San Francisco", "Columbus", "Charlotte", "Indianapolis", "Seattle", "Denver", "Washington", "Boston", "Miami", "Atlanta", "Las Vegas", "Detroit", "Portland"),
    "CA" to listOf("Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Saskatoon", "Regina"),
    "MX" to listOf("Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "Cancún", "Querétaro", "Chihuahua", "San Luis Potosí", "Acapulco"),
    "GT" to listOf("Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla", "Chinautla", "Chimaltenango", "Huehuetenango", "Antigua Guatemala", "Cobán"),
    "BZ" to listOf("Belize City", "San Ignacio", "Orange Walk", "Belmopan", "Dangriga", "Corozal", "San Pedro", "Benque Viejo", "Punta Gorda", "Placencia"),
    "SV" to listOf("San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Mejicanos", "Santa Tecla", "Apopa", "Delgado", "Sonsonate", "Ahuachapán"),
    "HN" to listOf("Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Choluteca", "Comayagua", "Puerto Cortés", "Danlí", "Siguatepeque"),
    "NI" to listOf("Managua", "León", "Masaya", "Chinandega", "Matagalpa", "Granada", "Estelí", "Tipitapa", "Jinotega", "Juigalpa"),
    "CR" to listOf("San José", "Alajuela", "Cartago", "Heredia", "Liberia", "Puntarenas", "Limón", "Desamparados", "San Isidro", "Pérez Zeledón"),
    "PA" to listOf("Panama City", "San Miguelito", "Tocumen", "David", "Arraiján", "Colón", "La Chorrera", "Santiago", "Chitré", "Penonomé"),
    "CU" to listOf("Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo", "Santa Clara", "Bayamo", "Cienfuegos", "Pinar del Río", "Matanzas"),
    "JM" to listOf("Kingston", "Spanish Town", "Portmore", "Montego Bay", "May Pen", "Mandeville", "Old Harbour", "Savanna-la-Mar", "Ocho Rios", "Port Antonio"),
    "HT" to listOf("Port-au-Prince", "Cap-Haïtien", "Carrefour", "Delmas", "Pétion-Ville", "Gonaïves", "Croix-des-Bouquets", "Les Cayes", "Jacmel", "Léogâne"),
    "DO" to listOf("Santo Domingo", "Santiago de los Caballeros", "Santo Domingo Este", "La Romana", "San Pedro de Macorís", "San Cristóbal", "Puerto Plata", "La Vega", "Higüey", "Moca"),
    "BS" to listOf("Nassau", "Freeport", "West End", "Coopers Town", "Marsh Harbour", "Freetown", "High Rock", "Andros Town", "George Town", "Alice Town"),
    "BB" to listOf("Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane", "Six Roads", "Bayville", "Blackmans", "Checker Hall"),
    "TT" to listOf("Port of Spain", "San Fernando", "Chaguanas", "Arima", "Point Fortin", "Scarborough", "Sangre Grande", "Couva", "Princes Town", "Tunapuna"),
    "GD" to listOf("St. George's", "Gouyave", "Grenville", "Victoria", "Sauteurs", "Hillsborough", "Grand Roy", "Birch Grove", "Marquis", "Tivoli"),
    "LC" to listOf("Castries", "Bisée", "Vieux Fort", "Micoud", "Soufrière", "Dennery", "Gros Islet", "Anse la Raye", "Choiseul", "Laborie"),
    "VC" to listOf("Kingstown", "Georgetown", "Byera", "Chateaubelair", "Barrouallie", "Layou", "Biabou", "Calliaqua", "Port Elizabeth", "Union Island"),
    "AG" to listOf("St. John's", "All Saints", "Liberta", "Potters Village", "Bolans", "Swetes", "Parham", "Falmouth", "Codrington", "Piggotts"),
    "DM" to listOf("Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut", "Wesley", "Salisbury", "Soufrière", "Grand Bay", "Castle Bruce"),
    "KN" to listOf("Basseterre", "Charlestown", "Sandy Point Town", "Cayon", "Dieppe Bay Town", "Fig Tree", "Newcastle", "Old Road Town", "Tabernacle", "Gingerland"),
    "BR" to listOf("São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Guarulhos", "Campinas", "São Luís"),
    "AR" to listOf("Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Neuquén"),
    "CL" to listOf("Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Iquique", "Puerto Montt", "Chillán"),
    "CO" to listOf("Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Ibagué", "Manizales", "Villavicencio"),
    "PE" to listOf("Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Chimbote", "Huancayo", "Tacna"),
    "VE" to listOf("Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "San Cristóbal", "Maturín", "Barcelona", "Puerto La Cruz"),
    "EC" to listOf("Guayaquil", "Quito", "Cuenca", "Santo Domingo", "Machala", "Durán", "Manta", "Portoviejo", "Loja", "Ambato"),
    "BO" to listOf("Santa Cruz de la Sierra", "La Paz", "El Alto", "Cochabamba", "Sucre", "Oruro", "Tarija", "Potosí", "Sacaba", "Montero"),
    "PY" to listOf("Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Limpio", "Ñemby", "Encarnación"),
    "UY" to listOf("Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes"),
    "GY" to listOf("Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Rosignol", "Mahaica", "Corriverton", "Parika"),
    "SR" to listOf("Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam", "Mariënburg", "Wageningen", "Albina", "Groningen", "Brokopondo"),
    "AU" to listOf("Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Wollongong", "Hobart", "Geelong", "Townsville", "Cairns", "Darwin"),
    "NZ" to listOf("Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua"),
    "FJ" to listOf("Suva", "Nadi", "Lautoka", "Labasa", "Nausori", "Ba", "Sigatoka", "Levuka", "Rakiraki", "Savusavu"),
    "PG" to listOf("Port Moresby", "Lae", "Mount Hagen", "Popondetta", "Madang", "Wewak", "Goroka", "Kokopo", "Kimbe", "Mendi"),
    "SB" to listOf("Honiara", "Auki", "Gizo", "Buala", "Kirakira", "Tulagi", "Lata", "Buin", "Munda", "Taro"),
    "VU" to listOf("Port Vila", "Luganville", "Norsup", "Isangel", "Sola", "Lakatoro", "Saratamata", "Longana", "Lenakel", "Ambae"),
    "WS" to listOf("Apia", "Vaitele", "Faleula", "Siusega", "Malie", "Vailoa", "Lalovaea", "Nofoalii", "Leauva'a", "Fasito'outa"),
    "TO" to listOf("Nuku'alofa", "Neiafu", "Haveluloto", "Vaini", "Pangai", "'Ohonua", "Kolonga", "Tofoa", "Longoteme", "Houma"),
)
